### ISSUE TITLE
Set output folder with a parameter instead of relying on gulp.dest

### ISSUE THREAD

**Issue by aorylamballe** [contra/gulp-concat#102]
gulp-concat seems to concatenate all files and put them in the folder of one of its input files (but not the first). This is harmful in my case when I pipe other tasks before writting the output folder. Example:

``` javascript
gulp.task('sass', function (done) {
	gulp.src(['./src/main.scss', './src/partials/**/*.scss'])
		.pipe(concat('dummy.scss'))
		//.pipe(gulp.dest('./src')) // sets the output folder of the concatenated file, used to process the next steps. e.g. for sass, resolve @import.
		.pipe(sass()) // Compile
		.pipe(minifyCss()) // Minify css
		.pipe(rename('styles.css')) // Set output name
		.pipe(gulp.dest('./dist/')) // Set output folder and write
		.on('end', done);
});
```

```sass()``` throws an error because main.scss contains @import that should be resolved relative to this file, i.e. ./src. But it tries to resolve from ./src/partials instead.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: src\partials\dummy.scss
  25:9  file to import not found or unreadable: lib/ionic/scss/ionic
Current dir:
    at options.error (C:\tfs\ionic-template\node_modules\node-sass\lib\index.js:276:32)
```

(the ```lib``` folder is in src, not ```partials```)

Here the workaround is to add a ```gulp.dest``` right after the concatenation. It does 2 things:

1. Sets the folder for the ```concat()``` output to use for the next pipes (e.g. how to resolve ```@import```s in ```sass()```
2. Write this file (I don't want it)

The 1. is OK, it prevents ```sass()``` from throwing an error because the main.scss @import are not resolved as expected. But the drawback is 2.: it generates an undesired ```./src/dummy.scss```.

An option for concat() setting the context folder (from where to resolve the subsequent pipes) would be great. Does it sound realistic?

Thanks for reading this!

**Comment by contra** [comment]
It should use the information from the first file for sure, would that solve your problem?

**Comment by aorylamballe** [comment]
That would be a way to solve my usecase, right.

Ideally, allowing to configure it would make it more flexible. Currently, the parameter is a string with the output file name. ```concat()``` could also use an object of configurations, e.g.

``` javascript
.pipe(concat({
  fileName: 'dummy.scss',
  folder: './src' // or 'src'
}))
```

And it would prepare for future extra configurations.

Just a suggestion. Using the first file path is okay for me :)

Thanks!

**Comment by contra** [comment]
Yeah, I think using an option if provided, else default to first file path is sane. I'd take a PR for this if anyone is interested.

**Comment by aorylamballe** [comment]
Thanks!

I tried to have a look at the code, and now I can't reproduce the problem any more :(. I may suggest a fix for the first part (use the first file by default), but I don't even know if it would solve my intermittent case.

I guess it is related to the following code:

``` javascript
if (!latestMod || file.stat && file.stat.mtime > latestMod) {
    latestFile = file;
    latestMod = file.stat && file.stat.mtime;
}
```

if a file was modified more recently, it is used as ```latestFile```, which is used to define the path. Just setting a ```firstFile``` in a separate variable for output path only could be a solution, but without test case, I cannot make sure it fixes what I met previously.

I come back if I meet it again :)

The option parameter could still be usefull, but less important.
