### ISSUE TITLE
Duplicate contents in minified file

### ISSUE THREAD

**Issue by riyasat** [contra/gulp-concat#110]
Hi,
I am testing MVC6 and tried gulp-concat in gulpfile.js. It worked pretty fine but has one problem I do not know if it's only me or someone else is also having that. The issue is it concatenate same file twice.
I added following code under

>var cssMinify = require('gulp-minify-css');
>var concat = require('gulp-concat');
>
>gulp.task('minifycss', function () {
>   gulp.src('./wwwroot/lib/font-awesome/font-awesome.css')
>     .pipe(cssMinify())
>     .pipe(concat("fontawesome-min.css"))
>     .pipe(gulp.dest('./wwwroot/app/font-awesome');
>}
>

Now the out put should be one minified file of font awesome which is working fine but when I look into the file content it display
![gulp-concat-error](https://cloud.githubusercontent.com/assets/5029964/11702334/186907f2-9ed6-11e5-8d70-ec9ae9da560a.JPG)

Can you please take a look what is happening. 

Thanks.

**Comment by contra** [comment]
Why are you using concat at all if you only have one file?

**Comment by contra** [comment]
We have a test that verifies the correct behavior for this, you probably have an issue somewhere else in your code.

Test: https://github.com/contra/gulp-concat/blob/master/test/main.js#L58-L64
