### ISSUE TITLE
Content duplicated when globbing

### ISSUE THREAD

**Issue by dmitrybelyakov** [contra/gulp-concat#116]
Hey!

I'm getting a weird issue when using globbing pattert to traverse a directory:

```javascript
  gulp.src('frontend/js/{,**/}*.js')
    .pipe(concat('app.js'))
    .pipe(gulp.dest(public/js/));
```

Specifically I'm getting concatenated content duplicated, and my code appears twice in the destination file. This works however:

```javascript
  gulp.src('frontend/js/**/*.js')
    .pipe(concat('app.js'))
    .pipe(gulp.dest(public/js/));
```

But in that case I need to change the pattern each time I decide to nest directories deeper.

I'm on gulp-concat v. 2.6.0

**Comment by contra** [comment]
Not an issue with concat, this is an issue with the globber. This should be opened here: https://github.com/gulpjs/vinyl-fs

**Comment by dmitrybelyakov** [comment]
Ok, sure.
