### ISSUE TITLE
how to contat files with path name alone but not in all?

### ISSUE THREAD

**Issue by ivanberry** [contra/gulp-concat#123]
What i should do to achieve like this?

## Before contat
![1](https://cloud.githubusercontent.com/assets/13112910/17927442/4a763da0-6a28-11e6-8aa2-fbc4b90e5599.PNG)

## After contat
![2](https://cloud.githubusercontent.com/assets/13112910/17927415/222d48b6-6a28-11e6-9892-47df120461de.PNG)

Thanks!

**Comment by contra** [comment]
Something like this:

```js
gulp.src('contat/**/*.css')
  .pipe(concat('all.css'))
  .pipe(rename((p) => {
    p.basename = `${p.dirname}.${p.basename}`
    return p
  }))
  .pipe(gulp.dest('some-folder'))
```

Support questions go on StackOverflow.
