### ISSUE TITLE
Problem with css from angular-toastr

### ISSUE THREAD

**Issue by dgrubelic** [contra/gulp-concat#127]
Hi there,

i have this gulp setup to compile all bower libraries into one big css:

```javascript
var gulp = require('gulp');
var mainBowerFiles = require('gulp-main-bower-files');
var concat = require('gulp-concat');
var gulpFilter = require('gulp-filter');
var uglifycss = require('gulp-uglifycss');
var plumber = require('gulp-plumber');

function errorHandler(err) {
  console.error(err);
}

gulp.task('libraries.css', function () {
  var filterCSS = gulpFilter('**/*.css', { restore: true });
  gulp.src('./bower.json')
    .on('error', errorHandler)
    .pipe(plumber(errorHandler))
    .pipe(mainBowerFiles())
    .pipe(filterCSS)
    .pipe(concat('libs.css'))
    .pipe(uglifycss())
    .pipe(gulp.dest('./public/styles'))
});
```

The problem is with `angular-toastr` who's css file contains base64 encoded image as background.

https://github.com/Foxandxss/angular-toastr
https://github.com/Foxandxss/angular-toastr/blob/master/dist/angular-toastr.css

**Comment by contra** [comment]
What exactly is the problem? You didn't include any information in your post.

My guess: doesn't have anything to do with gulp-concat - all it does is combine files, definitely does not care what is inside the files.
