### ISSUE TITLE
Don't working "gulp-watch" with "gulp-concat"

### ISSUE THREAD

**Issue by ivanprotsko** [contra/gulp-concat#131]
Tell me, please. Why don't work this code?

  gulp.task('scripts', function() {
    return gulp.src('build/js/**/*.js')
      .pipe(watch('build/js/**/*.js'))
      .pipe(concat('app.js'))
      .pipe(babel({
        presets: ['es2015']
      }))
      .pipe(gulp.dest('public/js/'))
      .pipe(livereload({ start: true }));
  });

Don't work Watch and Concat at the same time.

If delete row "", then Concat is working.

Do me a favor, tell me, how i can use "gulp-concat" with "gulp-watch"?

**Comment by contra** [comment]
Ask the gulp-watch people, no idea what they have going on over there. I think that plugin is blacklisted and unmaintained.
