### ISSUE TITLE
gulp-concat seems to sallow errors

### ISSUE THREAD

**Issue by ZachBray** [contra/gulp-concat#76]
Thank you for a very useful project!

I have an issue regarding errors not being propagated. Please consider the following snippet from my gulpfile:

        ...
        .on('error', function(err) {
            console.log("A!");
        })
        .pipe(concat('Sample.js'))
        .on('error', function (err) {
            console.log("B!");
        })
        ...

When there are any errors I see "A!" in the output. However, I do not see "B!" in the output (even if the first error handling section is omitted).

This means the exit code ends up being incorrect and this messes up my build integration.

**Comment by contra** [comment]
Node version?
