### ISSUE TITLE
Allow no argument?

### ISSUE THREAD

**Issue by tomekwi** [contra/gulp-concat#88]
Sometimes the name of the concatenated file doesn't matter. Like:

```js
var gulp = require("gulp");
var dox = require("gulp-dox");
var doxme = require("gulp-doxme");
var concat = require("gulp-concat");
var rename = require("gulp-rename");

gulp.src("**.js")
  .pipe(concat("anything"))
  .pipe(dox())
  .pipe(doxme())
  .pipe(rename("Readme.md"))
  .pipe(gulp.dest("."))
  ;
```

I understand `""` can't ever be a valid filename. But `undefined` casts to `"undefined"`, same with `null`. Why not allow them?

It shouldn't do any harm. When someone sees a file named `undefined` output to his `gulp.dest`, it's quite obvious what happened. Without throwing any error.

**Comment by contra** [comment]
I think it's confusing and not good API design to default an argument to "undefined" - sorry :(

**Comment by tomekwi** [comment]
A year later: I agree!

:+1:
